# _target_: icv_src.icv_encoder.global_icv_encoder.GlobalICVEncoder
_target_: icv_src.icv_encoder.global_lora_encoder.GlobalICVEncoderOuter

use_sigmoid: True
alpha_learnable: True
alpha_init_value: 0.