defaults:
  - _self_
  - data_cfg: icv_data


run_name: ???
device: 'cuda'

result_path: ${oc.env:RESULT_DIR}
model_cpk_dir: ${MODEL_CPK_DIR}
model_name: idefics-9b


icv_length: 4

hydra:
  run:
    dir: ${result_dir}/hydra_output/${hydra.job.name}/${run_name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${result_dir}/hydra_output/${hydra.job.name}/${run_name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
