defaults:
  - _self_
  - data_cfg: icv_data


run_name: ???
device: 'cuda'
result_dir: ${oc.env:RESULT_DIR}
val_ques_path: ${oc.env:VQAV2_PATH}/v2_OpenEnded_mscoco_val2014_questions.json
val_ann_path: ${oc.env:VQAV2_PATH}/v2_mscoco_val2014_annotations.json
result_path: ${oc.env:RESULT_DIR}

icv_length: 4

hydra:
  run:
    dir: ${result_dir}/hydra_output/${hydra.job.name}/${run_name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${result_dir}/hydra_output/${hydra.job.name}/${run_name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
