defaults:
  - _self_
  - data_cfg: icv_data


run_name: debug
device: 'cuda'

result_path: ${oc.env:RESULT_DIR}
model_cpk_dir: ${MODEL_CPK_DIR}
model_name: idefics-9b
alpha_value: 0.005
seed: 3407
icv_range: 4

hydra:
  run:
    dir: ${oc.env:RESULT_DIR}/hydra_output/${hydra.job.name}/${run_name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${oc.env:RESULT_DIR}/hydra_output/${hydra.job.name}/${run_name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
