defaults:
  - _self_
  - data_cfg: icv_data
  - trainer: zero2


module_cfg: 
  only_ans_loss: True
  strategy: ${trainer.strategy}
  lr: 1e-3
  weight_decay: 1e-3
  warm_steps: 0.1


seed: 426

run_name: "debug"

model_name_or_path: "${oc.env:MODEL_CPK_DIR}/idefics-9b"
# model_name: "HuggingFaceM4/tiny-random-idefics"

result_dir: ${oc.env:RESULT_DIR}


hydra:
  run:
    dir: ${result_dir}/hydra_output/${hydra.job.name}/${run_name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${result_dir}/hydra_output/${hydra.job.name}/${run_name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
