defaults:
  - _self_
  - data_cfg: icv_data


lora_qkv: False
bs: 4
test_num: -1
few_shot_list: [1, 2, 4, 8, 16, 32]

run_name: debug
result_dir: ${oc.env:RESULT_DIR}
device: 'cuda'

model_name_or_path: "${oc.env:MODEL_CPK_DIR}/idefics-9b"

hydra:
  run:
    dir: ${result_dir}/hydra_output/${hydra.job.name}/${run_name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${result_dir}/hydra_output/${hydra.job.name}/${run_name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
