defaults:
  - _self_
  - data_cfg: icv_data




bs: 4
test_num: -1
run_name: "global_icv_nonsig_alpha0.1_1wsample_32shot"
test_all_mean: False

result_dir: ${oc.env:RESULT_DIR}
device: 'cuda'

model_name_or_path: "${oc.env:MODEL_CPK_DIR}/idefics-9b"

hydra:
  run:
    dir: ${result_dir}/hydra_output/${hydra.job.name}/${run_name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${result_dir}/hydra_output/${hydra.job.name}/${run_name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
